# Generated by Django 5.2.3 on 2025-07-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
