# Generated by Django 5.2.3 on 2025-07-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_category_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='category',
        ),
    ]
