# Generated by Django 5.2.4 on 2025-07-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_name_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='photos/blogs'),
        ),
    ]
